version: '3.8'

services:
  postgres:
    image: postgres:15.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: autoinvest
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../schema/:/docker-entrypoint-initdb.d/

secrets:
   pg_password:
     file: ../.secrets/pg_password

volumes:
  postgres:
    driver: local
